// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: admission_control.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AdmissionControl {

  /// <summary>Holder for reflection information generated from admission_control.proto</summary>
  public static partial class AdmissionControlReflection {

    #region Descriptor
    /// <summary>File descriptor for admission_control.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdmissionControlReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdhZG1pc3Npb25fY29udHJvbC5wcm90bxIRYWRtaXNzaW9uX2NvbnRyb2wa",
            "FGdldF93aXRoX3Byb29mLnByb3RvGhRtZW1wb29sX3N0YXR1cy5wcm90bxoR",
            "dHJhbnNhY3Rpb24ucHJvdG8aD3ZtX2Vycm9ycy5wcm90byJIChhTdWJtaXRU",
            "cmFuc2FjdGlvblJlcXVlc3QSLAoKc2lnbmVkX3R4bhgBIAEoCzIYLnR5cGVz",
            "LlNpZ25lZFRyYW5zYWN0aW9uIuEBChlTdWJtaXRUcmFuc2FjdGlvblJlc3Bv",
            "bnNlEiQKCXZtX3N0YXR1cxgBIAEoCzIPLnR5cGVzLlZNU3RhdHVzSAASPgoJ",
            "YWNfc3RhdHVzGAIgASgOMikuYWRtaXNzaW9uX2NvbnRyb2wuQWRtaXNzaW9u",
            "Q29udHJvbFN0YXR1c0gAEj4KDm1lbXBvb2xfc3RhdHVzGAMgASgOMiQubWVt",
            "cG9vbC5NZW1wb29sQWRkVHJhbnNhY3Rpb25TdGF0dXNIABIUCgx2YWxpZGF0",
            "b3JfaWQYBCABKAxCCAoGc3RhdHVzKkUKFkFkbWlzc2lvbkNvbnRyb2xTdGF0",
            "dXMSDAoIQWNjZXB0ZWQQABIPCgtCbGFja2xpc3RlZBABEgwKCFJlamVjdGVk",
            "EAIy5wEKEEFkbWlzc2lvbkNvbnRyb2wScAoRU3VibWl0VHJhbnNhY3Rpb24S",
            "Ky5hZG1pc3Npb25fY29udHJvbC5TdWJtaXRUcmFuc2FjdGlvblJlcXVlc3Qa",
            "LC5hZG1pc3Npb25fY29udHJvbC5TdWJtaXRUcmFuc2FjdGlvblJlc3BvbnNl",
            "IgASYQoUVXBkYXRlVG9MYXRlc3RMZWRnZXISIi50eXBlcy5VcGRhdGVUb0xh",
            "dGVzdExlZGdlclJlcXVlc3QaIy50eXBlcy5VcGRhdGVUb0xhdGVzdExlZGdl",
            "clJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Types.GetWithProofReflection.Descriptor, global::Mempool.MempoolStatusReflection.Descriptor, global::Types.TransactionReflection.Descriptor, global::Types.VmErrorsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AdmissionControl.AdmissionControlStatus), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AdmissionControl.SubmitTransactionRequest), global::AdmissionControl.SubmitTransactionRequest.Parser, new[]{ "SignedTxn" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AdmissionControl.SubmitTransactionResponse), global::AdmissionControl.SubmitTransactionResponse.Parser, new[]{ "VmStatus", "AcStatus", "MempoolStatus", "ValidatorId" }, new[]{ "Status" }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Additional statuses that are possible from admission control in addition
  /// to VM statuses.
  /// </summary>
  public enum AdmissionControlStatus {
    [pbr::OriginalName("Accepted")] Accepted = 0,
    [pbr::OriginalName("Blacklisted")] Blacklisted = 1,
    [pbr::OriginalName("Rejected")] Rejected = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// -----------------------------------------------------------------------------
  /// ---------------- Submit transaction
  /// -----------------------------------------------------------------------------
  /// The request for transaction submission.
  /// </summary>
  public sealed partial class SubmitTransactionRequest : pb::IMessage<SubmitTransactionRequest> {
    private static readonly pb::MessageParser<SubmitTransactionRequest> _parser = new pb::MessageParser<SubmitTransactionRequest>(() => new SubmitTransactionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SubmitTransactionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AdmissionControl.AdmissionControlReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubmitTransactionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubmitTransactionRequest(SubmitTransactionRequest other) : this() {
      signedTxn_ = other.signedTxn_ != null ? other.signedTxn_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubmitTransactionRequest Clone() {
      return new SubmitTransactionRequest(this);
    }

    /// <summary>Field number for the "signed_txn" field.</summary>
    public const int SignedTxnFieldNumber = 1;
    private global::Types.SignedTransaction signedTxn_;
    /// <summary>
    /// Transaction signed by wallet.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Types.SignedTransaction SignedTxn {
      get { return signedTxn_; }
      set {
        signedTxn_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SubmitTransactionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SubmitTransactionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SignedTxn, other.SignedTxn)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (signedTxn_ != null) hash ^= SignedTxn.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (signedTxn_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SignedTxn);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (signedTxn_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SignedTxn);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SubmitTransactionRequest other) {
      if (other == null) {
        return;
      }
      if (other.signedTxn_ != null) {
        if (signedTxn_ == null) {
          SignedTxn = new global::Types.SignedTransaction();
        }
        SignedTxn.MergeFrom(other.SignedTxn);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (signedTxn_ == null) {
              SignedTxn = new global::Types.SignedTransaction();
            }
            input.ReadMessage(SignedTxn);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The response for transaction submission.
  ///
  /// How does a client know if their transaction was included?
  /// A response from the transaction submission only means that the transaction
  /// was successfully added to mempool, but not that it is guaranteed to be
  /// included in the chain.  Each transaction should include an expiration time in
  /// the signed transaction.  Let's call this T0.  As a client, I submit my
  /// transaction to a validator. I now need to poll for the transaction I
  /// submitted.  I can use the query that takes my account and sequence number. If
  /// I receive back that the transaction is completed, I will verify the proofs to
  /// ensure that this is the transaction I expected.  If I receive a response that
  /// my transaction is not yet completed, I must check the latest timestamp in the
  /// ledgerInfo that I receive back from the query.  If this time is greater than
  /// T0, I can be certain that my transaction will never be included.  If this
  /// time is less than T0, I need to continue polling.
  /// </summary>
  public sealed partial class SubmitTransactionResponse : pb::IMessage<SubmitTransactionResponse> {
    private static readonly pb::MessageParser<SubmitTransactionResponse> _parser = new pb::MessageParser<SubmitTransactionResponse>(() => new SubmitTransactionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SubmitTransactionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AdmissionControl.AdmissionControlReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubmitTransactionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubmitTransactionResponse(SubmitTransactionResponse other) : this() {
      validatorId_ = other.validatorId_;
      switch (other.StatusCase) {
        case StatusOneofCase.VmStatus:
          VmStatus = other.VmStatus.Clone();
          break;
        case StatusOneofCase.AcStatus:
          AcStatus = other.AcStatus;
          break;
        case StatusOneofCase.MempoolStatus:
          MempoolStatus = other.MempoolStatus;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubmitTransactionResponse Clone() {
      return new SubmitTransactionResponse(this);
    }

    /// <summary>Field number for the "vm_status" field.</summary>
    public const int VmStatusFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Types.VMStatus VmStatus {
      get { return statusCase_ == StatusOneofCase.VmStatus ? (global::Types.VMStatus) status_ : null; }
      set {
        status_ = value;
        statusCase_ = value == null ? StatusOneofCase.None : StatusOneofCase.VmStatus;
      }
    }

    /// <summary>Field number for the "ac_status" field.</summary>
    public const int AcStatusFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AdmissionControl.AdmissionControlStatus AcStatus {
      get { return statusCase_ == StatusOneofCase.AcStatus ? (global::AdmissionControl.AdmissionControlStatus) status_ : 0; }
      set {
        status_ = value;
        statusCase_ = StatusOneofCase.AcStatus;
      }
    }

    /// <summary>Field number for the "mempool_status" field.</summary>
    public const int MempoolStatusFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Mempool.MempoolAddTransactionStatus MempoolStatus {
      get { return statusCase_ == StatusOneofCase.MempoolStatus ? (global::Mempool.MempoolAddTransactionStatus) status_ : 0; }
      set {
        status_ = value;
        statusCase_ = StatusOneofCase.MempoolStatus;
      }
    }

    /// <summary>Field number for the "validator_id" field.</summary>
    public const int ValidatorIdFieldNumber = 4;
    private pb::ByteString validatorId_ = pb::ByteString.Empty;
    /// <summary>
    /// Public key(id) of the validator that processed this transaction
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ValidatorId {
      get { return validatorId_; }
      set {
        validatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private object status_;
    /// <summary>Enum of possible cases for the "status" oneof.</summary>
    public enum StatusOneofCase {
      None = 0,
      VmStatus = 1,
      AcStatus = 2,
      MempoolStatus = 3,
    }
    private StatusOneofCase statusCase_ = StatusOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatusOneofCase StatusCase {
      get { return statusCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearStatus() {
      statusCase_ = StatusOneofCase.None;
      status_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SubmitTransactionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SubmitTransactionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VmStatus, other.VmStatus)) return false;
      if (AcStatus != other.AcStatus) return false;
      if (MempoolStatus != other.MempoolStatus) return false;
      if (ValidatorId != other.ValidatorId) return false;
      if (StatusCase != other.StatusCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (statusCase_ == StatusOneofCase.VmStatus) hash ^= VmStatus.GetHashCode();
      if (statusCase_ == StatusOneofCase.AcStatus) hash ^= AcStatus.GetHashCode();
      if (statusCase_ == StatusOneofCase.MempoolStatus) hash ^= MempoolStatus.GetHashCode();
      if (ValidatorId.Length != 0) hash ^= ValidatorId.GetHashCode();
      hash ^= (int) statusCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (statusCase_ == StatusOneofCase.VmStatus) {
        output.WriteRawTag(10);
        output.WriteMessage(VmStatus);
      }
      if (statusCase_ == StatusOneofCase.AcStatus) {
        output.WriteRawTag(16);
        output.WriteEnum((int) AcStatus);
      }
      if (statusCase_ == StatusOneofCase.MempoolStatus) {
        output.WriteRawTag(24);
        output.WriteEnum((int) MempoolStatus);
      }
      if (ValidatorId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ValidatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (statusCase_ == StatusOneofCase.VmStatus) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VmStatus);
      }
      if (statusCase_ == StatusOneofCase.AcStatus) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AcStatus);
      }
      if (statusCase_ == StatusOneofCase.MempoolStatus) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MempoolStatus);
      }
      if (ValidatorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ValidatorId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SubmitTransactionResponse other) {
      if (other == null) {
        return;
      }
      if (other.ValidatorId.Length != 0) {
        ValidatorId = other.ValidatorId;
      }
      switch (other.StatusCase) {
        case StatusOneofCase.VmStatus:
          if (VmStatus == null) {
            VmStatus = new global::Types.VMStatus();
          }
          VmStatus.MergeFrom(other.VmStatus);
          break;
        case StatusOneofCase.AcStatus:
          AcStatus = other.AcStatus;
          break;
        case StatusOneofCase.MempoolStatus:
          MempoolStatus = other.MempoolStatus;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Types.VMStatus subBuilder = new global::Types.VMStatus();
            if (statusCase_ == StatusOneofCase.VmStatus) {
              subBuilder.MergeFrom(VmStatus);
            }
            input.ReadMessage(subBuilder);
            VmStatus = subBuilder;
            break;
          }
          case 16: {
            status_ = input.ReadEnum();
            statusCase_ = StatusOneofCase.AcStatus;
            break;
          }
          case 24: {
            status_ = input.ReadEnum();
            statusCase_ = StatusOneofCase.MempoolStatus;
            break;
          }
          case 34: {
            ValidatorId = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
