// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mempool_status.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mempool {

  /// <summary>Holder for reflection information generated from mempool_status.proto</summary>
  public static partial class MempoolStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for mempool_status.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MempoolStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRtZW1wb29sX3N0YXR1cy5wcm90bxIHbWVtcG9vbCqWAQobTWVtcG9vbEFk",
            "ZFRyYW5zYWN0aW9uU3RhdHVzEgkKBVZhbGlkEAASFwoTSW5zdWZmaWNpZW50",
            "QmFsYW5jZRABEhQKEEludmFsaWRTZXFOdW1iZXIQAhIRCg1NZW1wb29sSXNG",
            "dWxsEAMSFwoTVG9vTWFueVRyYW5zYWN0aW9ucxAEEhEKDUludmFsaWRVcGRh",
            "dGUQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Mempool.MempoolAddTransactionStatus), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MempoolAddTransactionStatus {
    /// <summary>
    /// Transaction was sent to Mempool
    /// </summary>
    [pbr::OriginalName("Valid")] Valid = 0,
    /// <summary>
    /// The sender does not have enough balance for the transaction.
    /// </summary>
    [pbr::OriginalName("InsufficientBalance")] InsufficientBalance = 1,
    /// <summary>
    /// Sequence number is old, etc.
    /// </summary>
    [pbr::OriginalName("InvalidSeqNumber")] InvalidSeqNumber = 2,
    /// <summary>
    /// Mempool is full (reached max global capacity)
    /// </summary>
    [pbr::OriginalName("MempoolIsFull")] MempoolIsFull = 3,
    /// <summary>
    /// Account reached max capacity per account
    /// </summary>
    [pbr::OriginalName("TooManyTransactions")] TooManyTransactions = 4,
    /// <summary>
    /// Invalid update. Only gas price increase is allowed
    /// </summary>
    [pbr::OriginalName("InvalidUpdate")] InvalidUpdate = 5,
  }

  #endregion

}

#endregion Designer generated code
